services:
  marznode:
    image: my-marznode:latest
    container_name: marznode
    restart: always
    network_mode: host
    command: [ "sh", "-c", "sleep 5 && python3 marznode.py" ]

    environment:
      SERVICE_PORT: "2344"
      XRAY_EXECUTABLE_PATH: "/var/lib/marznode/xray"
      XRAY_ASSETS_PATH: "/var/lib/marznode/data"
      XRAY_CONFIG_PATH: "/var/lib/marznode/xray_config.json"
      SSL_CLIENT_CERT_FILE: "/var/lib/marznode/client.pem"
      SSL_KEY_FILE: "./server.key"
      SSL_CERT_FILE: "./server.cert"
      INSECURE: "True"
      XRAY_RESTART_ON_FAILURE: "True"
      XRAY_RESTART_ON_FAILURE_INTERVAL: "5"
      AUTH_GENERATION_ALGORITHM: "plain"
    volumes:
      - /var/lib/marznode:/var/lib/marznode
      - /var/log/xray:/var/log/xray
